---
title: "Preview Activity 10"
author: "Liu"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here)
cereals <- read_csv(here("supporting_artifacts", 
                         "learning_targets",
                         "Preview 10", 
                         "cereal.csv"))
```

```{r}
cereals_long <- cereals|>
  pivot_longer("protein" : "fiber", names_to = "Nutrient", values_to = "Amount") |> 
  select(name, Nutrient, Amount)
cereals_long
```

```{r}
prof_info <- data.frame(
  professor = 
    c("Bodwin", "Glanz", "Carlton", "Sun", "Theobold"),
  undergrad_school = 
    c("Harvard", "Cal Poly", "Berkeley", "Harvard", "Colorado Mesa University"),
  grad_school = 
    c("UNC", "Boston University", "UCLA", "Stanford", "Montana State University")
)

prof_course <- data.frame(
  professor = c("Bodwin", "Glanz", "Carlton", "Theobold"),
  Stat_331 = c(TRUE, TRUE, TRUE, TRUE),
  Stat_330 = c(FALSE, TRUE, TRUE, FALSE),
  Stat_431 = c(TRUE, TRUE, FALSE, TRUE)
)

course_info <- data.frame(
  course = c("Stat_331", "Stat_330", "Stat_431"),
  num_sections = c(8, 3, 1)
)
```

```{r}
data_1 <- inner_join(prof_info, prof_course, by = "professor")
data_1
```

```{r}
data_2 <- left_join(prof_info, prof_course, by = "professor")
data_2
```

```{r}
prof_course_longer <- prof_course |> 
  pivot_longer("Stat_331":"Stat_431", names_to = 'course', values_to = 'can_teach')
data_3 <- full_join(prof_course_longer, course_info, by = "course")
data_3
```
