---
title: "My Growth as a Data Scientist"
author: "Austin Liu"
format: html
editor: visual
---

Data Science Concepts:

-   Coding

-   Data Visualizations

-   Data Analysis

-   Efficiency

As a Data scientist I grew by furthering my knowledge of R programming. I had originally come into this class with very limited experience in R programming, Python, and SAS. I feel much more comfortable in R compared to where I was before. I grew to like R much more than SAS, and I was also able to see similar aspects to pandas in Python. I became better at understanding a problem and visualizing in my head how to go about writing code that achieves it. After being exposed to and reading more code throughout the class, I have developed my own personal spacing style. I also have began to understand the meaning of code and the effects it may have on other variables.

Throughout this class, I have gotten experience coding different types of visualizations with ggplot and even explored new plots I had not seen before. I used a wide variety of data types and was able to be creative with the stylistic elements inside. My favorite stylistic elements that I learned were faceting and the color palettes. I thought the most useful thing we learned about visualizing data was learning how to use different elements to facet visualizations by variables using facet wraps, side-by-side format, and color-coding. Something that I improved on is understanding what types of plots are the best to show different data types.

I grew in my ability to do analysis on data, look for patterns, and show it. I learned how to further my knowledge of regression with broom::augment and broom::glance. The most interesting thing I learned was using ggplot to visualize data. I had previously learned how to plot using base R functions, so it was interesting to compare the differences.

I also grew to understand the importance of efficiency when looking at non-repetition in code as it relates to processing time and speed. Efficiency would also relate to tidy code and easy to read and understand. I expanded more on this principle in the efficiency essay, but it was also something quite important that was related to being a data scientist that I improved on.
