---
title: "The Power of Efficiency"
author: "Austin Liu"
format: html
editor: visual
---

Efficiency means the quickest process that achieves a goal that does not involve wasteful steps. In regards to statistical computing, this means the least amount of code to achieve a given task. This might mean non-repetitive function calls, storing intermediate objects when necessary, less inputs, or piping data. Efficient code also should be well spaced with the R code style guide that helps a reader understand code. Tidy code will also help the writer go back and easily understand what they did back then. Efficiency helps RStudio run code quicker.

I encountered efficiency in Lab 7, Part 2, Task 1, 2, and 3. In that part, we were tasked to create a re-scale function based on an equation. An a-ha moment for me was realizing I could store the min and max of a vector to an intermediate object so I would not need to use multiple min() function calls.

Another a-ha moment for me was earlier in the class, I would call multiple filter steps to perform filters on data. In my head, that made more sense to separate them. When I considered the idea of efficiency, I realized I was creating unnecessary steps to achieve something that could've been achieved in one filter step. An example of this is Lab 3 : Study Subjects.
